// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3c-CmgVWSmxMXmDpFXoqTYdjHoZaIi8Q',
    appId: '1:907646069825:web:97994d762f34d3f77faac0',
    messagingSenderId: '907646069825',
    projectId: 'flower-app-44ea6',
    authDomain: 'flower-app-44ea6.firebaseapp.com',
    storageBucket: 'flower-app-44ea6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASu8QAS68IxIrf1Pgvx2an52G-h1qjNlY',
    appId: '1:907646069825:android:7970770a8ab0f46f7faac0',
    messagingSenderId: '907646069825',
    projectId: 'flower-app-44ea6',
    storageBucket: 'flower-app-44ea6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjEKif4LOp72ne-wgNFDvHMeHqjuvAwi8',
    appId: '1:907646069825:ios:aba56adc22571c297faac0',
    messagingSenderId: '907646069825',
    projectId: 'flower-app-44ea6',
    storageBucket: 'flower-app-44ea6.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjEKif4LOp72ne-wgNFDvHMeHqjuvAwi8',
    appId: '1:907646069825:ios:aba56adc22571c297faac0',
    messagingSenderId: '907646069825',
    projectId: 'flower-app-44ea6',
    storageBucket: 'flower-app-44ea6.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3c-CmgVWSmxMXmDpFXoqTYdjHoZaIi8Q',
    appId: '1:907646069825:web:bc5bb8444c79f2d17faac0',
    messagingSenderId: '907646069825',
    projectId: 'flower-app-44ea6',
    authDomain: 'flower-app-44ea6.firebaseapp.com',
    storageBucket: 'flower-app-44ea6.appspot.com',
  );
}
